#+TITLE: Reproducing Spectre Attack with gem5, How To Do It Right?
#+AUTHOR: Pierre Ayoub
#+EMAIL: pierre.ayoub@eurecom.fr
#+LANGUAGE: en
#+PROPERTY: header-args :eval never-export
#+HTML_HEAD: <link rel="stylesheet" href="https://sandyuraz.com/styles/org.min.css">

* Introduction

  This web page is linked to the /[[https://github.com/pierreay/reproduce-spectre-gem5/blob/main/docs/paper.pdf][Reproducing Spectre Attack with gem5, How To
  Do It Right?]]/ paper, as well with the /[[https://github.com/pierreay/reproduce-spectre-gem5/blob/main/docs/report.pdf][Simulating Transient Execution Attacks
  with gem5]]/ master thesis.

  It will guide you through the reproduction of the experiments, the usage of
  our implementations or through the demonstration of some techniques discussed
  in the paper. You can navigate with the table of content, or directly click
  below to:
  - [[#howto_spectre][Learn how to perform a Spectre attack with our implementation]]
  - [[#howto_spectre][Learn how to simulate Spectre with gem5]]
  - [[#howto_konata][Learn how to visualize the pipeline of a simulated processor with Konata]]

* Repository

  This web page is part of the repository located [[https://github.com/pierreay/reproduce-spectre-gem5][here]]. See the =README.md=
  file for repository organization and navigation.

* HowTo ...
  
** How to Perform the Spectre Attack
   :PROPERTIES:
   :CUSTOM_ID: howto_spectre
   :END:

** How to Simulate Spectre with gem5
   :PROPERTIES:
   :CUSTOM_ID: howto_gem5
   :END:

** How to Visualize the Pipeline of a gem5 Processor with Konata
   :PROPERTIES:
   :CUSTOM_ID: howto_konata
   :END:

* Implementations

  Implementation details goes here.

** Spectre

** gem5
   
* Appendices

  - If you are a gem5 user who experience some unresolved errors, you could see
    the [[https://pierreay.github.io/reproduce-spectre-gem5/gem5_errors.html][=docs/gem5_errors.html=]] file.
